FROM ubuntu:latest 

RUN apt-get update -y && apt-get upgrade -y && \
    apt-get install -y nginx && \
    apt-get clean && rm -rf /var/lib/apt/lists/* /var/tmp/* /tmp/*

COPY site /var/www/html/

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]